services:
  app: 
    image: ghcr.io/$HIMTI-Binus-University/HIMTI_Internal-Frontend:${IMAGE_TAG}
    
    container_name: himti_frontend_${IMAGE_TAG} 
    restart: always
    
    ports:
      - "${FRONTEND_PORT}:80" # Mapping port dinamis (Dev:3000, Prod:80)

