FROM node:22-alpine AS builder

WORKDIR /app

COPY package*.json ./
RUN npm ci

COPY . .

ARG VITE_API_BASE_URL
ARG VITE_ADMIN_APP_URL
ARG VITE_LINK_APP_URL
ARG VITE_OFOG_URL
ARG VITE_REGISTRATION_APP_URL
ARG VITE_LOCAL_LINK_BASE_PATH

ENV VITE_API_BASE_URL=$VITE_API_BASE_URL
ENV VITE_ADMIN_APP_URL=$VITE_ADMIN_APP_URL
ENV VITE_LINK_APP_URL=$VITE_LINK_APP_URL
ENV VITE_OFOG_URL=$VITE_OFOG_URL
ENV VITE_REGISTRATION_APP_URL=$VITE_REGISTRATION_APP_URL
ENV VITE_LOCAL_LINK_BASE_PATH=$VITE_LOCAL_LINK_BASE_PATH

RUN npm run build

FROM nginx:1.27-alpine

COPY --from=builder /app/dist /usr/share/nginx/html
COPY nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
