/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  theme: {
    extend: {
      colors: {
        primary: {
          50: "#eeff6",
          100: "#c4cce4",
          200: "#a8b4d7",
          300: "#8091c5",
          400: "#677cb9",
          500: "#415ba8",
          600: "#3b5399",
          700: "#2e4177",
          800: "#24325c",
          900: "#1b2647",
        },
        grayscale: {
          50: "#f8f8f8",
          100: "#eaeaea",
          200: "#e0e0e0",
          300: "#d1d1d1",
          400: "#c9c9c9",
          500: "#bbbbbb",
          600: "#aaaaaa",
          700: "#858585",
          800: "#676767",
          900: "#4f4f4f",
        },
        danger: {
          400: "#e36a6a",
          500: "#d14545",
          600: "#b83a3a",
        },
        warning: {
          400: "#f5c84d",
          500: "#efb100",
          600: "#d39b00",
        },
        white: "#ffffff",
        black: "#000000",
        brand: {
          primary: {
            1: "#00214f",
            2: "#004cb5",
          },
          secondary: {
            1: "#7599ca",
            2: "#b6c5da",
            3: "#f8fafc",
          },
        },
        semantic: {
          background:             "#f8fafc",
          foreground:             "#101010",
          "primary-1":            "#004cb5",
          "primary-2":            "#00214f",
          "primary-foreground":   "#f8fafc",
          secondary:              "#b6c5da",
          "secondary-foreground": "#6a8ab6",
          input:                  "#f3f3f3",
          muted:                  "#e9e9e9",
          "muted-foreground":     "#b4b4b4",
          border:                 "#bdbdbd",
          warning:                "#ffb100",
          danger:                 "#dc2626",
          success:                "#16a34a",
        },
      },
      fontFamily: {
        sans: ["Public Sans", "sans-serif"],
        display: ["Plus Jakarta Sans", "sans-serif"],
      },
      fontSize: {
        h1: ["61px", { lineHeight: "92px", fontWeight: "400", letterSpacing: "0%" }],
        h2: ["49px", { lineHeight: "74px", fontWeight: "400", letterSpacing: "0%" }],
        h3: ["39px", { lineHeight: "59px", fontWeight: "400", letterSpacing: "0%" }],
        h4: ["31px", { lineHeight: "47px", fontWeight: "400", letterSpacing: "0%" }],
        h5: ["25px", { lineHeight: "38px", fontWeight: "400", letterSpacing: "0%" }],
        h6: ["20px", { lineHeight: "30px", fontWeight: "400", letterSpacing: "0%" }],
        "body-1": ["16px", { lineHeight: "24px", fontWeight: "400", letterSpacing: "0%" }],
        "body-2": ["13px", { lineHeight: "20px", fontWeight: "400", letterSpacing: "0%" }],
        "body-3": ["10px", { lineHeight: "15px", fontWeight: "400", letterSpacing: "0%" }],
        // Design system type scale (Plus Jakarta Sans)
        "ds-h1":                ["48px", { lineHeight: "48px", fontWeight: "800", letterSpacing: "-0.012em" }],
        "ds-h2":                ["30px", { lineHeight: "36px", fontWeight: "600", letterSpacing: "-0.0075em" }],
        "ds-h3":                ["24px", { lineHeight: "32px", fontWeight: "600", letterSpacing: "-0.006em" }],
        "ds-h4":                ["20px", { lineHeight: "28px", fontWeight: "600", letterSpacing: "-0.005em" }],
        "ds-large":             ["18px", { lineHeight: "28px", fontWeight: "600", letterSpacing: "0em" }],
        "ds-lead":              ["20px", { lineHeight: "28px", fontWeight: "400", letterSpacing: "0em" }],
        "ds-p":                 ["16px", { lineHeight: "28px", fontWeight: "400", letterSpacing: "0em" }],
        "ds-p-ui":              ["16px", { lineHeight: "24px", fontWeight: "400", letterSpacing: "0em" }],
        "ds-p-ui-medium":       ["16px", { lineHeight: "24px", fontWeight: "500", letterSpacing: "0em" }],
        "ds-list":              ["16px", { lineHeight: "24px", fontWeight: "400", letterSpacing: "0em" }],
        "ds-body":              ["14px", { lineHeight: "24px", fontWeight: "400", letterSpacing: "0em" }],
        "ds-body-medium":       ["14px", { lineHeight: "24px", fontWeight: "500", letterSpacing: "0em" }],
        "ds-subtle":            ["14px", { lineHeight: "20px", fontWeight: "400", letterSpacing: "0em" }],
        "ds-subtle-medium":     ["14px", { lineHeight: "20px", fontWeight: "500", letterSpacing: "0em" }],
        "ds-subtle-semibold":   ["14px", { lineHeight: "20px", fontWeight: "600", letterSpacing: "0em" }],
        "ds-small":             ["14px", { lineHeight: "14px", fontWeight: "500", letterSpacing: "0em" }],
        "ds-detail":            ["12px", { lineHeight: "20px", fontWeight: "500", letterSpacing: "0em" }],
        "ds-blockquote":        ["16px", { lineHeight: "24px", fontWeight: "400", letterSpacing: "0em" }],
        "ds-inline-code":       ["14px", { lineHeight: "20px", fontWeight: "700", letterSpacing: "0em" }],
        "ds-table-head":        ["16px", { lineHeight: "24px", fontWeight: "700", letterSpacing: "0em" }],
        "ds-table-item":        ["16px", { lineHeight: "24px", fontWeight: "400", letterSpacing: "0em" }],
        "ds-very-small":        ["10px", { lineHeight: "16px", fontWeight: "600", letterSpacing: "0.05em" }],
        "ds-very-small-extrabold": ["8px", { lineHeight: "16px", fontWeight: "800", letterSpacing: "0.05em" }],
      },
    },
  },
  plugins: [],
};
