/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  theme: {
    extend: {
      borderRadius: {
        lg: "var(--radius)",
        md: "calc(var(--radius) - 2px)",
        sm: "calc(var(--radius) - 4px)",
      },
      colors: {
        background: "hsl(var(--background))",
        foreground: "hsl(var(--foreground))",
        card: {
          DEFAULT: "hsl(var(--card))",
          foreground: "hsl(var(--card-foreground))",
        },
        popover: {
          DEFAULT: "hsl(var(--popover))",
          foreground: "hsl(var(--popover-foreground))",
        },
        muted: {
          DEFAULT: "hsl(var(--muted))",
          foreground: "hsl(var(--muted-foreground))",
        },
        accent: {
          DEFAULT: "hsl(var(--accent))",
          foreground: "hsl(var(--accent-foreground))",
        },
        destructive: {
          DEFAULT: "hsl(var(--destructive))",
          foreground: "hsl(var(--destructive-foreground))",
        },
        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        primary: {
          DEFAULT: "hsl(var(--primary))",
          foreground: "hsl(var(--primary-foreground))",
        },
        brand: {
          primary: {
            1: "#00214f",
            2: "#004cb5",
          },
          secondary: {
            1: "#7599ca",
            2: "#b6c5da",
            3: "#f8fafc",
          },
        },
        semantic: {
          background:             "#F7F9FC",
          foreground:             "#0F172A",
          "primary-1":            "#004cb5",
          "primary-2":            "#00214f",
          "primary-foreground":   "#ffffff",
          secondary:              "#F1F5F9",
          "secondary-foreground": "#475569",
          input:                  "#C5D0DE",
          muted:                  "#F1F5F9",
          "muted-foreground":     "#475569",
          border:                 "#D7DFEA",
          warning:                "#92400E",
          "warning-background":   "#FFFBEB",
          "warning-border":       "#FDE68A",
          danger:                 "#B91C1C",
          "danger-background":    "#FEF2F2",
          "danger-border":        "#FECACA",
          success:                "#166534",
          "success-background":   "#F0FDF4",
          "success-border":       "#BBF7D0",
          info:                   "#1D4ED8",
          "info-background":      "#EFF6FF",
          "info-border":          "#BFDBFE",
        },
        danger: {
          DEFAULT: "#B91C1C",
          background: "#FEF2F2",
          border: "#FECACA",
        },
      },
      fontFamily: {
        sans: ["Plus Jakarta Sans", "sans-serif"],
      },
      fontSize: {
        h1: ["61px", { lineHeight: "92px", fontWeight: "400", letterSpacing: "0%" }],
        h2: ["49px", { lineHeight: "74px", fontWeight: "400", letterSpacing: "0%" }],
        h3: ["39px", { lineHeight: "59px", fontWeight: "400", letterSpacing: "0%" }],
        h4: ["31px", { lineHeight: "47px", fontWeight: "400", letterSpacing: "0%" }],
        h5: ["25px", { lineHeight: "38px", fontWeight: "400", letterSpacing: "0%" }],
        h6: ["20px", { lineHeight: "30px", fontWeight: "400", letterSpacing: "0%" }],
        "body-1": ["16px", { lineHeight: "24px", fontWeight: "400", letterSpacing: "0%" }],
        "body-2": ["13px", { lineHeight: "20px", fontWeight: "400", letterSpacing: "0%" }],
        "body-3": ["10px", { lineHeight: "15px", fontWeight: "400", letterSpacing: "0%" }],
        // Design system type scale (Plus Jakarta Sans)
        "ds-h1":                ["48px", { lineHeight: "48px", fontWeight: "800", letterSpacing: "-0.012em" }],
        "ds-h2":                ["30px", { lineHeight: "36px", fontWeight: "600", letterSpacing: "-0.0075em" }],
        "ds-h3":                ["24px", { lineHeight: "32px", fontWeight: "600", letterSpacing: "-0.006em" }],
        "ds-h4":                ["20px", { lineHeight: "28px", fontWeight: "600", letterSpacing: "-0.005em" }],
        "ds-large":             ["18px", { lineHeight: "28px", fontWeight: "600", letterSpacing: "0em" }],
        "ds-lead":              ["20px", { lineHeight: "28px", fontWeight: "400", letterSpacing: "0em" }],
        "ds-p":                 ["16px", { lineHeight: "28px", fontWeight: "400", letterSpacing: "0em" }],
        "ds-p-ui":              ["16px", { lineHeight: "24px", fontWeight: "400", letterSpacing: "0em" }],
        "ds-p-ui-medium":       ["16px", { lineHeight: "24px", fontWeight: "500", letterSpacing: "0em" }],
        "ds-list":              ["16px", { lineHeight: "24px", fontWeight: "400", letterSpacing: "0em" }],
        "ds-body":              ["14px", { lineHeight: "24px", fontWeight: "400", letterSpacing: "0em" }],
        "ds-body-medium":       ["14px", { lineHeight: "24px", fontWeight: "500", letterSpacing: "0em" }],
        "ds-subtle":            ["14px", { lineHeight: "20px", fontWeight: "400", letterSpacing: "0em" }],
        "ds-subtle-medium":     ["14px", { lineHeight: "20px", fontWeight: "500", letterSpacing: "0em" }],
        "ds-subtle-semibold":   ["14px", { lineHeight: "20px", fontWeight: "600", letterSpacing: "0em" }],
        "ds-small":             ["14px", { lineHeight: "14px", fontWeight: "500", letterSpacing: "0em" }],
        "ds-detail":            ["12px", { lineHeight: "20px", fontWeight: "500", letterSpacing: "0em" }],
        "ds-blockquote":        ["16px", { lineHeight: "24px", fontWeight: "400", letterSpacing: "0em" }],
        "ds-inline-code":       ["14px", { lineHeight: "20px", fontWeight: "700", letterSpacing: "0em" }],
        "ds-table-head":        ["16px", { lineHeight: "24px", fontWeight: "700", letterSpacing: "0em" }],
        "ds-table-item":        ["16px", { lineHeight: "24px", fontWeight: "400", letterSpacing: "0em" }],
        "ds-very-small":        ["10px", { lineHeight: "16px", fontWeight: "600", letterSpacing: "0.05em" }],
        "ds-very-small-extrabold": ["8px", { lineHeight: "16px", fontWeight: "800", letterSpacing: "0.05em" }],
      },
    },
  },
  plugins: [],
};
