import type { LucideIcon } from "lucide-react";
import { AlertCircle, ArrowLeft, Check, Inbox, type LucideProps } from "lucide-react";
import { Link, NavLink } from "react-router-dom";
import { StatusBadge } from "@/components/events/StatusBadge";
import { Card, CardContent } from "@/components/ui/card";
import { cn } from "@/lib/utils";
import type { SubeventStatus } from "@/types/events";

export const EmptyState = ({ icon: Icon = Inbox, title, description, action }: { icon?: LucideIcon; title: string; description: string; action?: React.ReactNode }) => <Card><CardContent className="px-6 py-14 text-center"><span className="mx-auto flex h-12 w-12 items-center justify-center rounded-xl bg-muted text-muted-foreground"><Icon className="h-6 w-6" aria-hidden="true" /></span><h2 className="mt-4 text-lg font-semibold">{title}</h2><p className="mx-auto mt-2 max-w-md text-sm leading-6 text-muted-foreground">{description}</p>{action && <div className="mt-5 flex justify-center">{action}</div>}</CardContent></Card>;

export const StatCard = ({ label, value, detail, icon: Icon, tone = "default" }: { label: string; value: React.ReactNode; detail?: string; icon: LucideIcon; tone?: "default" | "warning" | "danger" | "success" }) => <Card className={cn(tone === "warning" && "border-semantic-warning-border", tone === "danger" && "border-semantic-danger-border", tone === "success" && "border-semantic-success-border")}><CardContent className="p-4"><div className="flex items-start justify-between gap-3"><div><p className="text-sm font-medium text-muted-foreground">{label}</p><p className="mt-1 text-2xl font-bold tracking-tight text-foreground">{value}</p>{detail && <p className="mt-1 text-xs leading-5 text-muted-foreground">{detail}</p>}</div><span className="flex h-9 w-9 shrink-0 items-center justify-center rounded-lg bg-muted text-primary"><Icon className="h-[18px] w-[18px]" aria-hidden="true" /></span></div></CardContent></Card>;

export const ProgressBar = ({ value, label }: { value: number; label: string }) => <div><div className="mb-2 flex justify-between text-xs font-medium text-muted-foreground"><span>{label}</span><span>{value}%</span></div><div className="h-2 overflow-hidden rounded-full bg-muted"><div className="h-full rounded-full bg-primary transition-[width] duration-300" style={{ width: `${value}%` }} /></div></div>;

export const WorkspaceHeader = ({ backTo, eyebrow, title, description, status, actions }: { backTo: string; eyebrow: string; title: string; description?: string; status?: SubeventStatus; actions?: React.ReactNode }) => <div className="mb-6 overflow-hidden rounded-xl border border-primary/15 bg-card shadow-sm"><div className="border-b border-border bg-primary px-5 py-5 text-primary-foreground sm:px-6"><Link to={backTo} className="inline-flex min-h-11 items-center gap-2 rounded-lg px-1 text-sm font-medium text-primary-foreground/75 hover:text-primary-foreground focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-white"><ArrowLeft className="h-4 w-4" />Back</Link><div className="mt-2 flex flex-col justify-between gap-4 lg:flex-row lg:items-end"><div><p className="text-xs font-bold uppercase tracking-[0.1em] text-primary-foreground/65">{eyebrow}</p><div className="mt-1 flex flex-wrap items-center gap-2"><h1 className="text-2xl font-bold tracking-tight sm:text-3xl">{title}</h1>{status && <StatusBadge status={status} />}</div>{description && <p className="mt-2 max-w-3xl text-sm leading-6 text-primary-foreground/75">{description}</p>}</div>{actions && <div className="flex flex-wrap gap-2">{actions}</div>}</div></div></div>;

export type WorkspaceSection = "overview" | "registration-setup" | "forms" | "payment" | "registrations";
export const WorkspaceTabs = ({ basePath, active }: { basePath: string; active: WorkspaceSection }) => { const tabs: { value: WorkspaceSection; label: string }[] = [{ value: "overview", label: "Overview" }, { value: "registration-setup", label: "Registration setup" }, { value: "forms", label: "Forms" }, { value: "payment", label: "Payment setup" }, { value: "registrations", label: "Registrations" }]; return <nav aria-label="Subevent workspace" className="mb-6 overflow-x-auto rounded-xl border border-border bg-card p-1.5 shadow-sm"><div className="flex min-w-max gap-1">{tabs.map((tab) => <NavLink key={tab.value} to={`${basePath}/${tab.value}`} className={cn("inline-flex min-h-11 items-center rounded-lg px-4 text-sm font-semibold transition-colors focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring", active === tab.value ? "bg-primary text-primary-foreground" : "text-muted-foreground hover:bg-muted hover:text-foreground")}>{tab.label}</NavLink>)}</div></nav>; };

export const SetupStepper = ({ active, completed }: { active: number; completed: number[] }) => { const labels = ["Details", "Registration", "Forms", "Payment", "Review"]; return <ol className="grid grid-cols-5 gap-2" aria-label="Subevent setup progress">{labels.map((label, index) => { const done = completed.includes(index); return <li key={label} className="min-w-0"><div className={cn("h-1.5 rounded-full", index === active ? "bg-primary" : done ? "bg-semantic-success" : "bg-muted")} /><div className="mt-2 flex items-center gap-1.5"><span className={cn("flex h-5 w-5 shrink-0 items-center justify-center rounded-full text-[10px] font-bold", index === active ? "bg-primary text-white" : done ? "bg-semantic-success text-white" : "bg-muted text-muted-foreground")}>{done ? <Check className="h-3 w-3" /> : index + 1}</span><span className="hidden truncate text-xs font-medium text-muted-foreground sm:block">{label}</span></div></li>; })}</ol>; };

export const Warning = ({ children }: { children: React.ReactNode }) => <div className="flex gap-3 rounded-lg border border-semantic-warning-border bg-semantic-warning-background p-3 text-sm leading-6 text-semantic-warning"><AlertCircle className="mt-0.5 h-4 w-4 shrink-0" aria-hidden="true" />{children}</div>;
export const IconBox = ({ icon: Icon, ...props }: { icon: React.ComponentType<LucideProps> } & React.HTMLAttributes<HTMLSpanElement>) => <span {...props} className={cn("flex h-10 w-10 shrink-0 items-center justify-center rounded-lg bg-muted text-primary", props.className)}><Icon className="h-5 w-5" /></span>;
